In [153]:
import pandas as pd
from pathlib import Path

In [154]:
data_folder = Path("../dataset")
# below paths should be realtive to data_folder
users_file_glob = "AllUsers.csv" 
ads_file_glob = "AllAds.csv"
final_dataset = "AllUsers_Ads_Ratings_df.csv"
derived_dataset = "AllUsers_Ads_Ratings_Fav_Unfav_Merged_df.csv"

In [155]:
df = pd.read_csv(data_folder/f"{users_file_glob}")

/Users/sasachde/.venv/py37/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2714: DtypeWarning: Columns (22,28,29,30,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [156]:
# environment settings 
# pd.set_option('display.max_column',None)
# pd.set_option('display.max_rows',None)
# pd.set_option('display.max_seq_items',None)
# pd.set_option('display.max_colwidth', 500)
# pd.set_option('expand_frame_repr', True)

In [157]:
df.head()

UserId    AdId  Age Cap/Zip-Code         Countries visited  \
0  U0001  A01_01   62        15613  United States of America   
1  U0001  A01_02   62        15613  United States of America   
2  U0001  A01_03   62        15613  United States of America   
3  U0001  A01_04   62        15613  United States of America   
4  U0001  A01_05   62        15613  United States of America   

            Fave Sports Gender              Home country Home town  Income  \
0  I do not like Sports      F  United States of America    Apollo       1   
1  I do not like Sports      F  United States of America    Apollo       1   
2  I do not like Sports      F  United States of America    Apollo       1   
3  I do not like Sports      F  United States of America    Apollo       1   
4  I do not like Sports      F  United States of America    Apollo       1   

  Last Name                   Most listened musics Most read books  \
0    Hidden  Classical Music, Easy Listening, Jazz         Mystery   
1    Hidden  Classical Music, Easy Listening, Jazz         Mystery   
2    Hidden  Classical Music, Easy Listening, Jazz         Mystery   
3    Hidden  Classical Music, Easy Listening, Jazz         Mystery   
4    Hidden  Classical Music, Easy Listening, Jazz         Mystery   

                                                                       Most visited websites  \
0  Media (Books, DVD, CD/DVD Music) sites, Grocery &amp; beverages sites, Pet supplies sites   
1  Media (Books, DVD, CD/DVD Music) sites, Grocery &amp; beverages sites, Pet supplies sites   
2  Media (Books, DVD, CD/DVD Music) sites, Grocery &amp; beverages sites, Pet supplies sites   
3  Media (Books, DVD, CD/DVD Music) sites, Grocery &amp; beverages sites, Pet supplies sites   
4  Media (Books, DVD, CD/DVD Music) sites, Grocery &amp; beverages sites, Pet supplies sites   

                        Most watched movies Most watched tv programmes  \
0  Action, Thriller, Drama, Comedy, Mystery              Comedy, Drama   
1  Action, Thriller, Drama, Comedy, Mystery              Comedy, Drama   
2  Action, Thriller, Drama, Comedy, Mystery              Comedy, Drama   
3  Action, Thriller, Drama, Comedy, Mystery              Comedy, Drama   
4  Action, Thriller, Drama, Comedy, Mystery              Comedy, Drama   

     Name              Paypal  Timepass             Type of Job  \
0  Hidden  hidden@comcast.net  Internet  Housewife/Househusband   
1  Hidden  hidden@comcast.net  Internet  Housewife/Househusband   
2  Hidden  hidden@comcast.net  Internet  Housewife/Househusband   
3  Hidden  hidden@comcast.net  Internet  Housewife/Househusband   
4  Hidden  hidden@comcast.net  Internet  Housewife/Househusband   

  Weekly working hours    fave1 fave10    fave2            fave3  \
0            Full Time  my cats    NaN  my cats  movie we are in   
1            Full Time  my cats    NaN  my cats  movie we are in   
2            Full Time  my cats    NaN  my cats  movie we are in   
3            Full Time  my cats    NaN  my cats  movie we are in   
4            Full Time  my cats    NaN  my cats  movie we are in   

               fave4            fave5 fave6 fave7 fave8 fave9         unfave1  \
0  tv show we are in  movie we are in   NaN   NaN   NaN   NaN  news headlines   
1  tv show we are in  movie we are in   NaN   NaN   NaN   NaN  news headlines   
2  tv show we are in  movie we are in   NaN   NaN   NaN   NaN  news headlines   
3  tv show we are in  movie we are in   NaN   NaN   NaN   NaN  news headlines   
4  tv show we are in  movie we are in   NaN   NaN   NaN   NaN  news headlines   

        unfave2   unfave3 unfave4       unfave5 unfave6  \
0  homelessness  violence     war  human rights     NaN   
1  homelessness  violence     war  human rights     NaN   
2  homelessness  violence     war  human rights     NaN   
3  homelessness  violence     war  human rights     NaN   
4  homelessness  violence     war  human rights     NaN   

                                                   

In [158]:
# Merge the cols into one

df["fav"] = df[['fave1', 'fave2','fave3', 'fave4','fave5']].apply(lambda x: ' '.join(x.map(str)), axis=1)
df["unfav"] = df[['unfave1', 'unfave2','unfave3', 'unfave4','unfave5']].apply(lambda x: ' '.join(x.map(str)), axis=1)

In [159]:
# Drop the cols now

favs = ['fave'+str(i) for i in range(1,11)]
unfavs = ['unfave'+str(i) for i in range(1,11)]

In [160]:
for fav in favs:
    df.drop(fav, inplace = True, axis=1)

In [ ]:
for unfav in unfavs:
    df.drop(unfav, inplace = True, axis=1)

In [ ]:
df.sample(10)

In [162]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36000 entries, 0 to 35999
Data columns (total 25 columns):
UserId                        36000 non-null object
AdId                          36000 non-null object
Age                           36000 non-null int64
Cap/Zip-Code                  36000 non-null object
Countries visited             36000 non-null object
Fave Sports                   36000 non-null object
Gender                        36000 non-null object
Home country                  36000 non-null object
Home town                     36000 non-null object
Income                        36000 non-null int64
Last Name                     36000 non-null object
Most listened musics          36000 non-null object
Most read books               36000 non-null object
Most visited websites         36000 non-null object
Most watched movies           36000 non-null object
Most watched tv programmes    36000 non-null object
Name                          36000 non-null object
Paypal   

In [163]:
# Save it back on disk
df.to_csv(data_folder/f"{derived_dataset}")

# Use embeddings

Here we can follow two approaches:<br/>
-     Use Embedding layer and pass pre trained glove embeddings and fine tune on it (This is what we will try out!)<br/>
-     Use glove to convert cols to vectors and store it back to disk (Manual way what we did for AI Hackathon)
-     Encode each column and make it part of the training. Needs separate layer for each cat col in our case fav and unfav 


Alternatively we can train embeddings on our dataset by using fav and unfav columns and a <br/>
making a dataset to train a embeddings capturing which words are positive ad which are negative<br/>
and then use that in our models.


## Use Embedding layer and pass pre trained glove embeddings

In [164]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import chakin
import json
import os
from collections import defaultdict
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Embedding

In [165]:
df = pd.read_csv(data_folder/f"{derived_dataset}")

Reference - https://github.com/balajibalasubramanian/Kaggle-Toxic-Comments-Challenge/blob/master/Keras%20lstm%201%20layer%20%2B%20GloVe%20%2B%20Early%20Stopping%20%2B%20attention%20%2B%20K-fold%20cross-validation.ipynb

In [166]:
# define text data
df_new = df['fav'].astype(str)

In [167]:
# initialize the tokenizer
t = Tokenizer()
t.fit_on_texts(df_new)

In [226]:
vocabulary_list = list(t.word_index .keys())

In [168]:
vocab_size = len(t.word_index) + 1
vocab_size

1168

In [169]:
# integer encode the text data
encoded_favs = t.texts_to_sequences(df_new)
encoded_favs

[[5, 22, 5, 22, 57, 82, 43, 13, 146, 147, 82, 43, 13, 57, 82, 43, 13],
 [5, 22, 5, 22, 57, 82, 43, 13, 146, 147, 82, 43, 13, 57, 82, 43, 13],
 [5, 22, 5, 22, 57, 82, 43, 13, 146, 147, 82, 43, 13, 57, 82, 43, 13],
 [5, 22, 5, 22, 57, 82, 43, 13, 146, 147, 82, 43, 13, 57, 82, 43, 13],
 [5, 22, 5, 22, 57, 82, 43, 13, 146, 147, 82, 43, 13, 57, 82, 43, 13],
 [5, 22, 5, 22, 57, 82, 43, 13, 146, 147, 82, 43, 13, 57, 82, 43, 13],
 [5, 22, 5, 22, 57, 82, 43, 13, 146, 147, 82, 43, 13, 57, 82, 43, 13],
 [5, 22, 5, 22, 57, 82, 43, 13, 146, 147, 82, 43, 13, 57, 82, 43, 13],
 [5, 22, 5, 22, 57, 82, 43, 13, 146, 147, 82, 43, 13, 57, 82, 43, 13],
 [5, 22, 5, 22, 57, 82, 43, 13, 146, 147, 82, 43, 13, 57, 82, 43, 13],
 [5, 22, 5, 22, 57, 82, 43, 13, 146, 147, 82, 43, 13, 57, 82, 43, 13],
 [5, 22, 5, 22, 57, 82, 43, 13, 146, 147, 82, 43, 13, 57, 82, 43, 13],
 [5, 22, 5, 22, 57, 82, 43, 13, 146, 147, 82, 43, 13, 57, 82, 43, 13],
 [5, 22, 5, 22, 57, 82, 43, 13, 146, 147, 82, 43, 13, 57, 82, 43, 13],
 [5, 2

In [170]:
maxlen = max(len(x) for x in encoded_favs ) 
maxlen

40

In [171]:
# pad the vectors to create uniform length
padded_favs = pad_sequences(encoded_favs, maxlen=maxlen, padding='post')
padded_favs

array([[   5,   22,    5, ...,    0,    0,    0],
       [   5,   22,    5, ...,    0,    0,    0],
       [   5,   22,    5, ...,    0,    0,    0],
       ...,
       [1162, 1163, 1164, ...,    0,    0,    0],
       [1162, 1163, 1164, ...,    0,    0,    0],
       [1162, 1163, 1164, ...,    0,    0,    0]], dtype=int32)

In [172]:
chakin.search(lang='English')

                   Name  Dimension                     Corpus VocabularySize  \
2          fastText(en)        300                  Wikipedia           2.5M   
11         GloVe.6B.50d         50  Wikipedia+Gigaword 5 (6B)           400K   
12        GloVe.6B.100d        100  Wikipedia+Gigaword 5 (6B)           400K   
13        GloVe.6B.200d        200  Wikipedia+Gigaword 5 (6B)           400K   
14        GloVe.6B.300d        300  Wikipedia+Gigaword 5 (6B)           400K   
15       GloVe.42B.300d        300          Common Crawl(42B)           1.9M   
16      GloVe.840B.300d        300         Common Crawl(840B)           2.2M   
17    GloVe.Twitter.25d         25               Twitter(27B)           1.2M   
18    GloVe.Twitter.50d         50               Twitter(27B)           1.2M   
19   GloVe.Twitter.100d        100               Twitter(27B)           1.2M   
20   GloVe.Twitter.200d        200               Twitter(27B)           1.2M   
21  word2vec.GoogleNews        300      

In [173]:
# Downloading Twitter.25d embeddings from Stanford:

CHAKIN_INDEX = 17
NUMBER_OF_DIMENSIONS = 25
SUBFOLDER_NAME = "glove.twitter.27B"

DATA_FOLDER = "embeddings"
ZIP_FILE = os.path.join(DATA_FOLDER, "{}.zip".format(SUBFOLDER_NAME))
ZIP_FILE_ALT = "glove" + ZIP_FILE[5:]  # sometimes it's lowercase only...
UNZIP_FOLDER = os.path.join(DATA_FOLDER, SUBFOLDER_NAME)
if SUBFOLDER_NAME[-1] == "d":
    GLOVE_FILENAME = os.path.join(UNZIP_FOLDER, "{}.txt".format(SUBFOLDER_NAME))
else:
    GLOVE_FILENAME = os.path.join(UNZIP_FOLDER, "{}.{}d.txt".format(SUBFOLDER_NAME, NUMBER_OF_DIMENSIONS))


if not os.path.exists(ZIP_FILE) and not os.path.exists(UNZIP_FOLDER):
    # GloVe by Stanford is licensed Apache 2.0: 
    #     https://github.com/stanfordnlp/GloVe/blob/master/LICENSE
    #     http://nlp.stanford.edu/data/glove.twitter.27B.zip
    #     Copyright 2014 The Board of Trustees of The Leland Stanford Junior University
    print("Downloading embeddings to '{}'".format(ZIP_FILE))
    chakin.download(number=CHAKIN_INDEX, save_dir='./{}'.format(DATA_FOLDER))
else:
    print("Embeddings already downloaded.")
    
if not os.path.exists(UNZIP_FOLDER):
    import zipfile
    if not os.path.exists(ZIP_FILE) and os.path.exists(ZIP_FILE_ALT):
        ZIP_FILE = ZIP_FILE_ALT
    with zipfile.ZipFile(ZIP_FILE,"r") as zip_ref:
        print("Extracting embeddings to '{}'".format(UNZIP_FOLDER))
        zip_ref.extractall(UNZIP_FOLDER)
else:
    print("Embeddings already extracted.")

Embeddings already downloaded.
Embeddings already extracted.


In [174]:
# load the glove embedding into memory after downloading and unzippping

embeddings_index = dict()
print("Reading Glove embeddings from ", GLOVE_FILENAME)
f = open(GLOVE_FILENAME, encoding="utf8")

for line in f:
    # Note: use split(' ') instead of split() if you get an error.
    values = line.split(' ')
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()
print('Loaded %s word vectors.' % len(embeddings_index))

# create a weight matrix
embedding_matrix = np.zeros((vocab_size, NUMBER_OF_DIMENSIONS))
for word, i in t.word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector

Reading Glove embeddings from  embeddings/glove.twitter.27B/glove.twitter.27B.25d.txt
Loaded 1193514 word vectors.


In [175]:
# Test the shape

embedding_matrix.shape
assert vocab_size == embedding_matrix.shape[0],"Vocab size not matching the shape[0] of embeddings"
assert NUMBER_OF_DIMENSIONS == embedding_matrix.shape[1],"Vocab size not matching the shape[1] of embeddings"

In [176]:
# Check first few items in embedding matrix

count  = 0
for word, i in t.word_index.items():
    print(word)
    count = count +1
    if count == 10:
        break

cute
food
love
family
my
and
music
nature
friends
art


### Use in the model

In [197]:
import numpy as np
import pandas as pd

import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow import feature_column
from tensorflow.keras import layers

In [198]:
# Working on subset of columns(one of each type)

In [199]:
df.columns

Index(['Unnamed: 0', 'UserId', 'AdId', 'Age', 'Cap/Zip-Code',
       'Countries visited', 'Fave Sports', 'Gender', 'Home country',
       'Home town', 'Income', 'Last Name', 'Most listened musics',
       'Most read books', 'Most visited websites', 'Most watched movies',
       'Most watched tv programmes', 'Name', 'Paypal', 'Timepass',
       'Type of Job', 'Weekly working hours', 'AdFilePath', 'Rating', 'fav',
       'unfav'],
      dtype='object')

In [204]:
df_new = df.filter(['Age','Gender','fav','Rating'], axis=1)
df_new.columns

Index(['Age', 'Gender', 'fav', 'Rating'], dtype='object')

In [205]:
train, test = train_test_split(df_new, test_size=0.2)
train, val = train_test_split(train, test_size=0.2)
print(len(train), 'train examples')
print(len(val), 'validation examples')
print(len(test), 'test examples')

23040 train examples
5760 validation examples
7200 test examples


In [208]:
# A utility method to create a tf.data dataset from a Pandas Dataframe

def df_to_dataset(dataframe, shuffle=True, batch_size=32):
  dataframe = dataframe.copy()
  labels = dataframe.pop('Rating')
  ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
  if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe))
  ds = ds.batch(batch_size)
  return ds

In [209]:
batch_size = 5 # A small batch sized is used for demonstration purposes
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

============= START: Try out a demo (ignore this section) =============

In [212]:
# We will use this batch to demonstrate several types of feature columns
example_batch = next(iter(train_ds))[0]

In [217]:
example_batch

{'Age': <tf.Tensor: shape=(5,), dtype=int32, numpy=array([24, 61, 46, 20, 40], dtype=int32)>,
 'Gender': <tf.Tensor: shape=(5,), dtype=string, numpy=array([b'F', b'F', b'F', b'M', b'M'], dtype=object)>,
 'fav': <tf.Tensor: shape=(5,), dtype=string, numpy=
 array([b'love, romance, couple, relationship horse, wild, powerful, chocolate, treat, indulgence, enjoyment nature, peaceful, natural ownership, control, trust',
        b"mom's Toyota Corolla sis at dinner birthday brunch mom's Barrie house old family home",
        b'Kita cats cuddles naps camping wilderness quiet nature smoking weed relaxation Kevin Smith movies funny smart watching ocean waves water',
        b'tennis racket tennis ball nature hiking family brother driving car',
        b'Mexican Soccer team IPad Mini 2 Football Pizza TV HD'],
       dtype=object)>}

In [213]:
# A utility method to create a feature column
# and to transform a batch of data
def demo(feature_column):
  feature_layer = layers.DenseFeatures(feature_column)
  print(feature_layer(example_batch).numpy())

In [214]:
# Numerical column

age = feature_column.numeric_column("Age")
demo(age)

[[24.]
 [61.]
 [46.]
 [20.]
 [40.]]


In [218]:
# Categorical column

gender = feature_column.categorical_column_with_vocabulary_list(
      'Gender', ['M', 'F'])

thal_one_hot = feature_column.indicator_column(gender)
demo(thal_one_hot)

[[0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]]


In [228]:
categorical_voc = tf.feature_column.categorical_column_with_vocabulary_list(key="fav", vocabulary_list=vocabulary_list)

#embedding_initializer = tf.random_uniform_initializer(-1.0, 1.0)
#initializer=embedding_initializer,
# embed_column_dim = math.ceil(len(vocabulary_list) ** 0.25)

embed_column = tf.feature_column.embedding_column(
    categorical_column=categorical_voc,
    dimension=NUMBER_OF_DIMENSIONS,
    trainable=True)

============= END : Try out a demo (ignore this section) =============

In [229]:
feature_columns = []

# numeric cols
for header in ['Age']:
  feature_columns.append(feature_column.numeric_column(header))

# indicator cols
gender = feature_column.categorical_column_with_vocabulary_list(
      'Gender', ['M', 'F'])
gender_one_hot = feature_column.indicator_column(gender)
feature_columns.append(gender_one_hot)

# embedding cols
categorical_voc = tf.feature_column.categorical_column_with_vocabulary_list(key="fav", vocabulary_list=vocabulary_list)

embed_column = tf.feature_column.embedding_column(
    categorical_column=categorical_voc,
    dimension=NUMBER_OF_DIMENSIONS,
    trainable=True)

In [230]:
# Create a feature layer

feature_layer = tf.keras.layers.DenseFeatures(feature_columns)

In [234]:
# Compile and train the model

model = tf.keras.Sequential([
  feature_layer,
  layers.Dense(128, activation='relu'),
  layers.Dense(128, activation='relu'),
  layers.Dense(1)
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.fit(train_ds,
          validation_data=val_ds,
          epochs=5)

Train for 4608 steps, validate for 1152 steps
Epoch 1/5
4608/4608 [==============================] - 6s 1ms/step - loss: -5692233.2340 - accuracy: 0.5525 - val_loss: -19947402.2483 - val_accuracy: 0.5550
Epoch 2/5
4608/4608 [==============================] - 6s 1ms/step - loss: -57595425.7502 - accuracy: 0.5525 - val_loss: -108972248.7066 - val_accuracy: 0.5550
Epoch 3/5
4608/4608 [==============================] - 5s 1ms/step - loss: -195353176.2849 - accuracy: 0.5525 - val_loss: -298520119.8472 - val_accuracy: 0.5550
Epoch 4/5
4608/4608 [==============================] - 6s 1ms/step - loss: -448072712.2378 - accuracy: 0.5525 - val_loss: -619077928.6667 - val_accuracy: 0.5550
Epoch 5/5
4608/4608 [==============================] - 6s 1ms/step - loss: -848080754.1510 - accuracy: 0.5525 - val_loss: -1099493185.8472 - val_accuracy: 0.5550


In [ ]:
loss, accuracy = model.evaluate(test_ds)
print("Accuracy", accuracy)

In [237]:
df1 = pd.DataFrame([[26,'M',[5, 22, 5, 22, 57, 82, 43, 13, 146, 147, 82, 43, 13, 57, 82, 43, 13]]])

In [238]:
model.predict(df1)

ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 3 array(s), for inputs ['Age', 'Gender', 'fav'] but instead got the following list of 1 arrays: [array([[26, 'M',
        list([5, 22, 5, 22, 57, 82, 43, 13, 146, 147, 82, 43, 13, 57, 82, 43, 13])]],
      dtype=object)]...

### In progress section

In [177]:
# define model

model = Sequential()
e = Embedding(vocab_size, NUMBER_OF_DIMENSIONS, weights=[embedding_matrix], input_length = maxlen, trainable=False)
model.add(e)
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [143]:
# compile the model

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [144]:
# summarize the model

print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 40, 25)            29200     
_________________________________________________________________
flatten_1 (Flatten)          (None, 1000)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 1001      
Total params: 30,201
Trainable params: 1,001
Non-trainable params: 29,200
_________________________________________________________________
None


// TODO: Use existing dataset and try a model
    Include more cols here using TF guide that was shared on slack

In [ ]:
# fit the model

model.fit(padded_favs, labels, epochs=50, verbose=0)

In [ ]:
# evaluate the model

loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

### References

In [ ]:
https://machinelearningmastery.com/use-word-embedding-layers-deep-learning-keras/
https://machinelearningmastery.com/how-to-prepare-categorical-data-for-deep-learning-in-python/
https://github.com/guillaume-chevalier/GloVe-as-a-TensorFlow-Embedding-Layer/blob/master/README.md